// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTc1fFAoHbCOCA4Q2Q35LO0Ju1H8BerZM',
    appId: '1:414170553736:android:3f93686db3baa9f4f92e3d',
    messagingSenderId: '414170553736',
    projectId: 'primax-ebb0c',
    storageBucket: 'primax-ebb0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXCUC2HiimXAZ1kV25rT7wlmURbJUtE-o',
    appId: '1:414170553736:ios:9822b3f7a7d20d53f92e3d',
    messagingSenderId: '414170553736',
    projectId: 'primax-ebb0c',
    storageBucket: 'primax-ebb0c.firebasestorage.app',
    androidClientId: '414170553736-6j6funmtb30eenjkm4adakirj2v1b9ll.apps.googleusercontent.com',
    iosClientId: '414170553736-ds93kjlh3595ke68kaq9fh5ifcal8tvs.apps.googleusercontent.com',
    iosBundleId: 'com.primaxsolarenergy.primax',
  );
}
